DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS magic;

CREATE TABLE magic (
  id SERIAL PRIMARY KEY,
  location_name VARCHAR NOT NULL UNIQUE,
  last_updated DATE NOT NULL,
  sunrise VARCHAR NOT NULL,
  sunset VARCHAR NOT NULL
);

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR NOT NULL UNIQUE,
  phone VARCHAR NOT NULL,
  zip VARCHAR NOT NULL,
  password_digest VARCHAR NOT NULL
);

